# Generated by Django 4.2.1 on 2023-09-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(default='/media/recipes/covers/2023/08/03/close-up-da-face-de-uma-mariposa-700-11845437.jpg', upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
